//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComsumirWCF.ClienteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/DemosWCF")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteServiceReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObtenerClientes", ReplyAction="http://tempuri.org/IClienteService/ObtenerClientesResponse")]
        ComsumirWCF.ClienteServiceReference.Cliente[] ObtenerClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObtenerClientes", ReplyAction="http://tempuri.org/IClienteService/ObtenerClientesResponse")]
        System.Threading.Tasks.Task<ComsumirWCF.ClienteServiceReference.Cliente[]> ObtenerClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/InsertarCliente", ReplyAction="http://tempuri.org/IClienteService/InsertarClienteResponse")]
        string InsertarCliente(ComsumirWCF.ClienteServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/InsertarCliente", ReplyAction="http://tempuri.org/IClienteService/InsertarClienteResponse")]
        System.Threading.Tasks.Task<string> InsertarClienteAsync(ComsumirWCF.ClienteServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarCliente", ReplyAction="http://tempuri.org/IClienteService/ModificarClienteResponse")]
        string ModificarCliente(ComsumirWCF.ClienteServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarCliente", ReplyAction="http://tempuri.org/IClienteService/ModificarClienteResponse")]
        System.Threading.Tasks.Task<string> ModificarClienteAsync(ComsumirWCF.ClienteServiceReference.Cliente c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/EliminarCliente", ReplyAction="http://tempuri.org/IClienteService/EliminarClienteResponse")]
        string EliminarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/EliminarCliente", ReplyAction="http://tempuri.org/IClienteService/EliminarClienteResponse")]
        System.Threading.Tasks.Task<string> EliminarClienteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : ComsumirWCF.ClienteServiceReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<ComsumirWCF.ClienteServiceReference.IClienteService>, ComsumirWCF.ClienteServiceReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ComsumirWCF.ClienteServiceReference.Cliente[] ObtenerClientes() {
            return base.Channel.ObtenerClientes();
        }
        
        public System.Threading.Tasks.Task<ComsumirWCF.ClienteServiceReference.Cliente[]> ObtenerClientesAsync() {
            return base.Channel.ObtenerClientesAsync();
        }
        
        public string InsertarCliente(ComsumirWCF.ClienteServiceReference.Cliente c) {
            return base.Channel.InsertarCliente(c);
        }
        
        public System.Threading.Tasks.Task<string> InsertarClienteAsync(ComsumirWCF.ClienteServiceReference.Cliente c) {
            return base.Channel.InsertarClienteAsync(c);
        }
        
        public string ModificarCliente(ComsumirWCF.ClienteServiceReference.Cliente c) {
            return base.Channel.ModificarCliente(c);
        }
        
        public System.Threading.Tasks.Task<string> ModificarClienteAsync(ComsumirWCF.ClienteServiceReference.Cliente c) {
            return base.Channel.ModificarClienteAsync(c);
        }
        
        public string EliminarCliente(int id) {
            return base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarClienteAsync(int id) {
            return base.Channel.EliminarClienteAsync(id);
        }
    }
}
